name: nice_flutter_kit
description: A collection of nice widgets
version: 2.6.4
homepage: https://github.com/Recursyve/nice_flutter_kit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  collection: ^1.17.2
  dio: ^5.3.3
  equatable: ^2.0.5
  expandable: ^5.0.1
  flutter_bloc: ^8.1.3
  flutter_keyboard_visibility: ^6.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  introduction_screen: ^3.1.12
  path: ^1.8.3
  permission_handler: ^11.0.0
  provider: ^6.0.5
  reactive_forms: ^16.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  timeago: ^3.5.0
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  uuid: ^4.4.2
  synchronized: ^3.1.0+1

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  test: ^1.25.2
